### ISSUE TITLE
Support for word boundries

### ISSUE THREAD

**Issue by JesterOrNot** [maciejhirsz/logos#125]
when writing a regex using word boundaries I get this

![image](https://user-images.githubusercontent.com/50386709/79793063-9aa0c200-8315-11ea-837a-d4964e683e3e.png)

Is there any plan to support something like this?

**Comment by maciejhirsz** [comment]
Possibly, at least at the tail position, but it's far down on my list. Word boundries are a bit of a performance foot gun since they need to either backtrack or look-ahead, and AFAIU like `\w` they would have to expand into full unicode matching graph for all unicode alphabets, which tends to bloat the state machine.

What is it that you are syntax highlighting there that you need them?

**Comment by JesterOrNot** [comment]
I'm trying to highlight keywords

typically I would do

\bkeyword\b

right now keywordfoo highlights keyword and it should not highlight at all

**Comment by JesterOrNot** [comment]
OK, I read the blog and added a new regex.

FYI The lexer expands to 
```rust
enum TheLexer {
    #[end]
    End,
    #[error]
    Error,
    #[token = " "]
    Whitespace,
    #[regex = "red"]
    Red,
    #[regex = "green"]
    Green,
    #[regex = "blue"]
    Blue,
    #[regex = "[a-zA-Z0-9_$]+"]
    NoHighlight,
}
```

This fixes a lot, thanks however there are still a few more issues here is the state of highlighting.

![image](https://user-images.githubusercontent.com/50386709/79807821-a601e680-8331-11ea-986f-b65a4d321fc7.png)

**Comment by maciejhirsz** [comment]
That looks like a bug! Let me check this out.

**Comment by maciejhirsz** [comment]
@JesterOrNot you'll need to upgrade to 0.11, this has been already fixed.

I've [added a test for this](https://github.com/maciejhirsz/logos/commit/98e2a2521642a6a910e46381ca687e97b2d186b8), and [it's passing](https://github.com/maciejhirsz/logos/actions/runs/83575601).

**Comment by JesterOrNot** [comment]
How would I translate this
```rust
while tokens.token != $enumName::End
```
to 0.11

**Comment by JesterOrNot** [comment]
i.e. how can I check the current token before I would use tokens.token()

**Comment by maciejhirsz** [comment]
`Lexer` is an iterator now. You could wrap it in [`peekable`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.peekable), though in this case you don't need to check since there is no end token anymore, you can just do:

```rust
for token in lexer {
// ...
}

// Or, if you want to keep using the lexer:

while let Some(token) = lexer.next() {
// ...
}
```

If you post a link to the code you are having troubles with I can help out with upgrading. If there is something missing in the API that would make things more ergonomic for more use cases, it would also be good to know :)

**Comment by JesterOrNot** [comment]
https://github.com/JesterOrNot/SynTerm I have been using logos as a compile to target for a lexer generator generator, the idea is to easily add syntax highlighting for any repl or shell. I've been using macros to generate the lexer struct

**Comment by maciejhirsz** [comment]
Yeah, so for 0.11 you change this:

```rust
            while tokens.token != $enumName::End {
                match tokens.token {
                    $(
                        $enumName::$token => print!("\x1b[{}m{}\x1b[m", $ansi, tokens.slice()),
                    )*
                    _ => print!("{}", tokens.slice())
                }
                tokens.advance();
            }
```

To this:
```rust
            while let Some(token) = tokens.next() {
                match token {
                    $(
                        $enumName::$token => print!("\x1b[{}m{}\x1b[m", $ansi, tokens.slice()),
                    )*
                    _ => print!("{}", tokens.slice())
                }
            }
```

And remove the end variant, it's no longer necessary since `next` returns `Option<YourEnum>`:
```rust
            #[end]
            End,
```

**Comment by JesterOrNot** [comment]
Thank you so much for all the help :)

**Comment by maciejhirsz** [comment]
Thanks for using Logos :)
