### ISSUE TITLE
Logos should error on compile time on regexes it can't properly match

### ISSUE THREAD

**Issue by maciejhirsz** [maciejhirsz/logos#140]
Following [this conversation](https://github.com/maciejhirsz/logos/issues/126#issuecomment-619441936) from #126, it's possible to construct a regex that will produce a state machine graph which would never produce a match ~given that Logos never backtracks across loop boundaries~. Logos should be able to detect such behavior and reject such regex for the same reasons it rejects regex with non-greedy flag `?`.

**Comment by CAD97** [comment]
> Require backtracking

This formulation of the problem is strictly incorrect. The regex `[01]*1` in no way requires backtracking to properly test. What it does require is that the naive translation of the regex to a finite automaton is nondeterministic, and then that NFA is transformed into a DFA or simulated in parallel (rather than backtracking to the choice).

The whole field of regular languages is basically about isomorphism between (nonextended) regex (basically what `regex-syntax` accepts), NFAs, and DFAs.

The `regex` crate contains no backtracking, and always matches in O(length of input) time. It handles `[01]*1` perfectly fine.

Maybe more directly to the point, `regex-automata` directly exposes the underlying automata, and can compile/simulate the regex string `[01]*1` as a linear DFA, without the optional trickery `regex` does.

If you cannot match `[01]*1`, you've not implemented regex, you've provided a PEG parser for regular grammars that uses a regex syntax.

Sorry to dump a load of terminology on you, but clarity of terminology is important here.

**Comment by maciejhirsz** [comment]
> If you cannot match `[01]*1`, you've not implemented regex, you've provided a PEG parser for regular grammars that uses a regex syntax.

Yup. To be clear: it was never my intent to implement a complete regex engine for Logos, but I did want to use the syntax since most developers are familiar with at least the basics of it. My whole goal here was for someone to be able to look at the example, and grok what this thing does without reading any documentation.

This can (probably will) change as Logos matures and as I dive deeper into the rabbit hole, but for now I'm happy to formalize the limits of the current implementation.

> Sorry to dump a load of terminology on you, but clarity of terminology is important here.

No need to apologize. Your contributions and insight have been nothing but helpful!
