### ISSUE TITLE
Work on raw bytes

### ISSUE THREAD

**Issue by birkenfeld** [maciejhirsz/logos#15]
As always with lexing/parsing, it would be very useful to have a mode that works on non-UTF8 byte slices.

It is probably easy to extend and implement `Source` for `&[u8]`, but that is obviouly only half of what's needed. Literals should be able to be specified in terms of byte literals, and regexes should be able to match literal bytes.

**Comment by maciejhirsz** [comment]
The entire thing actually operates on raw bytes internally, so that should be doable. The `Source` trait previously had an associated `Slice` type for what slices of it can be, but I've now locked it to a `&str`. I can revert that, but I need to think about ergonomics for some things around that currently would assume `&str` slices for tokens.

**Comment by CAD97** [comment]
The "simple" solution is similar to how nom does it:

- The `Source` trait is an abstraction for a slice of parsable input
- `Source` required behaviors:
  - subslice into smaller `Source` based on byte indexes
  - reference as byte slice for parsing machinery

Then any consumer of the output (which is currently receiving `&'source str`) would instead receive the `impl Source` type that the lexer was given. Thus, existing lexers where the `Source` type is `&str` would retain the same (monomorphized) API, but providing byte slices would allow the various callbacks to receive byte slices.

**Comment by birkenfeld** [comment]
Thanks for #25, but I think it's only half the way done? There is no way to match a literal `b'\xff'` byte, for example.

**Comment by maciejhirsz** [comment]
Right, I guess you really want it to parse arbitrary binary data (as opposed to say a text that is assumed utf8 or ascii without being converted to `&str`)?

A major issue here is that the `Lexer` reserves the byte value `0` for termination of input, which is fine for virtually all text inputs, but is likely to break plenty of binary formats. There is also the smaller issue in that creating a `Lexer` from `&str` if arbitrary bytes are have been put in token definitions should cause the `Lexer` to panic immediately.

I think this is solvable by making the "use `0` as termination optimization" an optional thing for non-binary inputs, but I'll have to think how to do this without breaking things horribly.

**Comment by birkenfeld** [comment]
Yes, "no null bytes" is even more of a restriction, but even for text formats it should be possible to lex non-UTF8 encoded inputs.

**Comment by timsueberkrueb** [comment]
> I think this is solvable by making the "use 0 as termination optimization" an optional thing for non-binary inputs, but I'll have to think how to do this without breaking things horribly.

I think that this should be optional for text formats as well - maybe even off by default - because it might lead to surprising bugs/behavior. Example: We ran into it when trying to build [a demo JSON parser](https://github.com/timsueberkrueb/yalr/pull/8) compliant against [this test suite](https://github.com/nst/JSONTestSuite/). 
This example is supposed to fail parsing (the character between `123` and `something` be `\u0000`):
```
#[test]
fn n_multidigit_number_then_00dotjso() {
    assert!(Parser::parse_str(r#"123 something"#).is_err());
}
``` 
But since Logos emits the `End` token for the null byte, it passes with the result `Ok(123)`.
Assuming my interpretation of this problem is right, please correct me if I'm wrong :)

**Comment by maciejhirsz** [comment]
@timsueberkrueb no, you are 100% correct.

This whole thing is only really an optimization around `NulTermStr` from `toolshed`. I can probably move the whole logic over to reading bytes there. The performance for regular `&str` or `&[u8]` sources should remain unaffected.

**Comment by maciejhirsz** [comment]
This is now done in #57 with [tests](https://github.com/maciejhirsz/logos/blob/ad7b3045968632366bcf5f567ba3b5064df5acff/tests/src/binary.rs) and will be part of the big 0.10 release.

* You can set binary token definitions with byte literals: `#[token = b"\xCA\xFE"]`.
* Same for regular expressions: `#[regex = b"[\xAA-\xBB]+"]`.
