### ISSUE TITLE
Subpatterns within subpatterns

### ISSUE THREAD

**Issue by ExoticMatter** [maciejhirsz/logos#162]
It would be nice if subpatterns could be used within subpatterns.

```rust
#[derive(Logos, Copy, Clone, Debug)]
#[logos(subpattern a = r"[a-zA-Z!$%&*/:<=>?^_~]")]
#[logos(subpattern b = r"(?&a)|[0-9+\-.@]")]
pub enum Token {
    #[error]
    Error,
    // ...
}
```

Currently, this is not supported and causes a regex parse error.

**Comment by Jezza** [comment]
I just hit this use case.
It'll simplify [this](https://github.com/maciejhirsz/logos/issues/133#issuecomment-687164347) massive monster dramatically.

**Comment by Jezza** [comment]
I'm taking a look at the subpattern code, and from what I can see, there's two solutions.

1. While we're "fixing" the variant's regex, we perform checks from the start of the string again, rather than the end of the previous replacement.

2. After adding all of the subpatterns, we perform a collapse of all of the subpatterns, iterating over all of them, and replacing all of the nested subpatterns as before.

**Comment by maciejhirsz** [comment]
@Jezza solution 1 sounds like a better choice for me - this happens at compile time so performance costs aren't the biggest priority, and it shouldn't really be very slow at all. The only bad scenario I can think of is some cyclical references that would need to be broken else the compiler is going to spin in an infinite loop.

**Comment by CAD97** [comment]
@Jezza if you're still interested in doing this, I think it should be as simple as running the "fix" path on each subpattern as we collect them. This would enforce that subpatterns only reference prior subpatterns (preventing cyclic definitions) and avoid significantly altering the logic flow.

**Comment by evbo** [comment]
Does the concept of a fixed string (no regex pattern) exist for "sub" components of a regular token? Could that be added?

I have tokens that are composed of smaller tokens, I know I could handle this in the parser but it feels cleaner defining them as separate:

```rust
#[token("\"")]
Quote,

#[token("Quote \\")]
EndQuote,
```

**Comment by Jezza** [comment]
@evbo I imagine that it would be straight forward to do, but you'd still need to use the `(?&<name>)` pattern, otherwise, it could just be a valid regex.

It would also raise the question of what happens when you have a conflicting subpattern.
Are all tokens suddenly subpatterns?
Seems a bit implicit.

**Comment by Jezza** [comment]
@CAD97 Yeah, that seems like a much better solution.

I've thrown together a short PR that shows that it works quite nicely.

Relatively clean, and actually ended up deleting more code than what I added, so that's a plus.

**Comment by evbo** [comment]
awesome!: https://github.com/maciejhirsz/logos/pull/237
