### ISSUE TITLE
Can I parse to specific token?

### ISSUE THREAD

**Issue by kdy1** [maciejhirsz/logos#172]
I'm currently trying to apply logos to the swc project.
Current lexer has lots of functions like `read_jsx_str`, which can be called only in the jsx context.

So I want to request for jsx tokens in some context. Is there an easy way to do this?
Also, I can skip space only in some contexts

**Comment by maciejhirsz** [comment]
That really depends on how you are writing the parser for the lexer. You could morph the lexer between different definitions, but that means using multiple enums. The best way is, I think, to just make sure all tokens for all contexts are defined, and just treat anything that isn't an expected token in a given context an error.

As to skipping whitespace, depending on your goals, you can use [extras with some skipping functions](https://github.com/maciejhirsz/logos/blob/cc26afc3a3ce28ea88c63699c06c0e27fc90fc92/tests/tests/simple.rs#L5-L28) that flag internally whether or not a space (or newline, since those are important in JS) has occurred prior to token.

If you give more concrete examples of what you're trying to do, I might be of more help.

**Comment by kdy1** [comment]
Thanks!

I'm trying to port the logic at https://github.com/swc-project/swc/blob/3a26d3d34dcbcaee30dc700a385dd18b7427e3d2/ecmascript/parser/src/lexer/jsx.rs#L83-L113 to logos.

When the lexer meet `&`, it **tries** to lex it as a jsx entity, by 

 1. consume input until `;`
 2. If it starts with `&#`, try parsing it as hex or decimal value
 3. If not, check if it is xhtml entity like `&lt`
 4. If not, reset input to position of '&' and emit `$` token (for BitAnd)


There are more methods which tries to read escaped characters, but those are similar.
