### ISSUE TITLE
"\".*\"" regex seems to be not working.

### ISSUE THREAD

**Issue by Sniadekk** [maciejhirsz/logos#175]
Hello!

I'm having some trouble to debug why my regex isn't working. 
Is it a mistake on my end or might it be a bug?

Code to reproduce the problem:

```rust
use logos::Logos;

#[derive(Logos, Debug)]
enum Token {
    #[regex("\".*\"", | lex | lex.slice().parse())]
    Text(String),
    #[error]
    Err,
}

fn main() {
    let lexer: Vec<_> = Token::lexer(r#""string literal""#).collect(); 
    println!("{:#?}", lexer);
    // expected [Token::Text(""string literal"")]
    // received  [Err] 
}
```

The regex I used seems to be [working just fine in the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4e4f0ced1304c1574c77857708e564b3).

**Comment by maciejhirsz** [comment]
Hey @Sniadekk, Logos isn't using the regex crate, only using the syntax. You're getting an error because `.` can match the tailing quote, to make it work you'd have to do `#[regex("\"[^\"]*\"", ...)]`.

**Comment by Sniadekk** [comment]
Thank you for the clarification!

**Comment by saruman9** [comment]
> Hey @Sniadekk, Logos isn't using the regex crate, only using the syntax. You're getting an error because `.` can match the tailing quote, to make it work you'd have to do `#[regex("\"[^\"]*\"", ...)]`.

@maciejhirsz, is it described somewhere? This behavior came as a surprise to me.

Also I don't understand the following situation:
```rust
use logos::Logos;
use regex::Regex;

const INPUT_WITH_WHITESPACE: &str = r#"TEST "test1 test2""#;
const INPUT_WITHOUT_WHITESPACE: &str = r#"TEST "test1test2""#;

#[derive(Logos, Debug, PartialEq)]
enum Token {
    #[regex(r#"([0-9A-Za-z_]+)\s+"(.*)""#)]
    Define,
    // #[regex(r"([0-9A-Za-z_]+)\s+(\S+)")]
    // Define1,
    #[error]
    Error,
}

#[test]
fn logos_regex_with_whitespace() {
    let mut lex = Token::lexer(INPUT_WITH_WHITESPACE);
    assert_eq!(Some(Token::Define), lex.next());
}

#[test]
fn regex_match_with_whitespace() {
    let re = Regex::new(r#"([0-9A-Za-z_]+)\s+"(.*)""#).unwrap();
    assert!(re.is_match(INPUT_WITH_WHITESPACE));
}

#[test]
fn logos_regex_without_whitespace() {
    let mut lex = Token::lexer(INPUT_WITHOUT_WHITESPACE);
    assert_eq!(Some(Token::Define), lex.next());
}

#[test]
fn regex_match_without_whitespace() {
    let re = Regex::new(r#"([0-9A-Za-z_]+)\s+"(.*)""#).unwrap();
    assert!(re.is_match(INPUT_WITHOUT_WHITESPACE));
}
```
Tests `logos_regex_with_whitespace` and `logos_regex_without_whitespace` will fail, if the `Define1` token is commented and only `logos_regex_with_whitespace` will fail if the `Define1` is not commented.

**Comment by maciejhirsz** [comment]
@saruman9 `INPUT_WITHOUT_WHITESPACE` can match both `Define` and `Define1`, that is either regex will produce a full match on that input, how should Logos know which one you intended to be the right choice? Since the lengths are different you don't get a compile error, but instead [token disambiguation](https://github.com/maciejhirsz/logos#token-disambiguation) will give `Define` will have a higher priority due to its length (more specific beats more generic). If you give `Define1` a higher priority it should work properly I reckon.

**Comment by saruman9** [comment]
Thank you for quick response.

> `INPUT_WITHOUT_WHITESPACE` can match both `Define` and `Define1`

But if I understood correctly your previous answer, `INPUT_WITHOUT_WHITESPACE` can't match `Define`, because `.*` can match the tailing quote too and the tailing quote in regex will not be match anything.

**Comment by maciejhirsz** [comment]
> Thank you for quick response.
> 
> > `INPUT_WITHOUT_WHITESPACE` can match both `Define` and `Define1`
> 
> But if I understood correctly your previous answer, `INPUT_WITHOUT_WHITESPACE` can't match `Define`, because `.*` can match the tailing quote too and the tailing quote in regex will not be match anything.

Ah right, it's been a while since I commented on this so I lost that context :). With both definitions uncommented, you can think of the lexer following rules for `INPUT_WITH_WHITESPACE` like this:

```
    | Define        | Define1
T   | [0-9A-Za-z_]+ | [0-9A-Za-z_]+
E   | [0-9A-Za-z_]+ | [0-9A-Za-z_]+
S   | [0-9A-Za-z_]+ | [0-9A-Za-z_]+
T   | [0-9A-Za-z_]+ | [0-9A-Za-z_]+
    | \s+           | \s+
"   | "             | \S+
t   | .*            | \S+
e   | .*            | \S+
s   | .*            | \S+
t   | .*            | \S+
1   | .*            | \S+
    | .*            | NO LONGER MATCHES
t   | .*
e   | .*
s   | .*
t   | .*
2   | .*
"   | .*
EOF | Expected ", failed match
```

`INPUT_WITHOUT_WHITESPACE` will match correctly to `Define1` since the error at the end of `Define` path will fall back to the second matching pattern, but once you add a space there, then there is nowhere else to go at that point.

**Comment by saruman9** [comment]
Thank you for detailed clarification. I think the same way you do, that `Define1` will match in case `INPUT_WITHOUT_WHITESPACE`, but it is not and it's strange.
The test:
```rust
#[test]
fn logos_regex_without_whitespace() {
    let mut lex = Token::lexer(INPUT_WITHOUT_WHITESPACE);
    assert_eq!(Some(Token::Define), lex.next());
}
```
passed (I compare with the `Define` token).

**Comment by maciejhirsz** [comment]
That's because of the priority for disambiguation. This works for me:

```rust
mod whitespace {
    use logos::Logos;

    const INPUT_WITH_WHITESPACE: &str = r#"TEST "test1 test2""#;
    const INPUT_WITHOUT_WHITESPACE: &str = r#"TEST "test1test2""#;

    #[derive(Logos, Debug, PartialEq)]
    enum Token {
        #[regex(r#"([0-9A-Za-z_]+)\s+"([^"]*)""#)] // matching [^"] to avoid the failed lexing
        Define,
        #[regex(r"([0-9A-Za-z_]+)\s+(\S+)", priority = 100)] // arbitrary high value to prioritize Define1 if there are no spaces
        Define1,
        #[error]
        Error,
    }

    #[test]
    fn logos_regex_with_whitespace() {
        let mut lex = Token::lexer(INPUT_WITH_WHITESPACE);
        assert_eq!(Some(Token::Define), lex.next()); // Define because of the space
    }

    #[test]
    fn logos_regex_without_whitespace() {
        let mut lex = Token::lexer(INPUT_WITHOUT_WHITESPACE);
        assert_eq!(Some(Token::Define1), lex.next()); // Define1 because either one matches, but Define1 has priority
    }
}
```

**Comment by saruman9** [comment]
I understand the regex are equivalent and need to set priority, but I mean another problem...

> 1. `Define` was never producing a valid match because of `.*"` at the end.

I mean exactly this problem.
```rust
use logos::Logos;

const INPUT_WITHOUT_WHITESPACE: &str = r#"TEST "test1test2""#;

#[derive(Logos, Debug, PartialEq)]
enum Token {
    #[regex(r#"([0-9A-Za-z_]+)\s+"(.*)""#)]
    Define,
    #[regex(r"([0-9A-Za-z_]+)\s+(\S+)")]
    Define1,
    #[error]
    Error,
}

#[test]
fn logos_regex_without_whitespace() {
    let mut lex = Token::lexer(INPUT_WITHOUT_WHITESPACE);
    assert_eq!(Some(Token::Define), lex.next());
}
```
Test will pass.

**Comment by maciejhirsz** [comment]
Ah, I see what you mean. What is happening here is:

1. It lexes `Define` till the error, then falls back to `Define1`.
2. `Define1` at this branch overlaps with `Define`, so token disambiguation forces the result to be `Define`.

That's why when you comment out `Define1` it stops working. Token disambiguation isn't aware that `Define1` is an invalid pattern that always errors, it only resolves pattern vs pattern at compile time (which is different to matching an input to a pattern).

Ideally what should happen here is a compile time error telling you that `Define` is never going to produce a valid result, with a suggestion on how to fix it.

**Comment by saruman9** [comment]
Oh, this was unexpected behavior for me! Thank you for your patience to explain everything to me.

**Comment by maciejhirsz** [comment]
Yeah, that's a pretty interesting edge case you found, I can't say I predicted this, definitely something that can be done better :)
