### ISSUE TITLE
Bad lexing when using generic regex ".+"

### ISSUE THREAD

**Issue by ghpu** [maciejhirsz/logos#186]
On logos v 0.11.4 , I can't lex simple characters as token, they are captured by the global regex .+ , even if I use priority :

Test case ; 

```rust
#[test]
  fn test() {
      use logos::Logos; 
      #[derive(Logos, Debug, PartialEq)]
      enum Token {
      #[error]
      ERROR,
      #[token("c", priority = 100)]
      COMMENT,
      #[regex(".+")]
      VALUE,
      ROOT,
  }
  let mut lex = Token::lexer("cc");
  assert_eq!(lex.next(), Some(Token::COMMENT));
  }
```

**Comment by maciejhirsz** [comment]
This is working as intended, priority is only used to disambiguate patterns, in your case there is no ambiguity for inputs longer than 2. You can fix that by excluding strings that begin with `c` from your `VALUE`: `[^c].*`.

**Comment by ghpu** [comment]
Thanks. There is still something I don't understand then, why is "cc" treated as a VALUE and not 2 COMMENT tokens ?
Is there implicit other rule that tokens should be space (or otherwise) separated ?

**Comment by maciejhirsz** [comment]
Sort of. The way to think about it is that the lexer is trying all currently matching patterns to find the longest possible match. If your input was just a single `c` then both patterns would match (which is where priority comes in), but since there are still bytes to read, and the second `c` matches `.`, that's the token you get.

**Comment by ghpu** [comment]
Thank you for your clear explanations !
