### ISSUE TITLE
Not lexing string literals properly

### ISSUE THREAD

**Issue by evandp** [maciejhirsz/logos#188]
I stumbled upon an issue when trying to lex string literals with the pattern `\".*\"`. Logos returns `Token::Error` for any string literal I've tried (including the empty string). The following is my token enum, the relevant callback and some basic driver code:

```rust
#[derive(Logos, Debug, PartialEq)]
pub enum Token {
    #[regex(r"[a-zA-Z]([a-zA-Z0-9]|'|_)*", ident)]
    Identifier(String),

    #[regex(r"[0-9]*", |lex| lex.slice().parse())]
    Integer(u64),

    #[regex(r"'.'", character)]
    Character(char),

    #[regex(r#"".*""#, string)]
    String(String),

    #[error]
    #[regex(r"[ \t\n\f]+", logos::skip)]
    Error,
}

fn string(lex: &mut LogosLexer<TokenType>) -> Option<String> {
    let slice = lex.slice();
    let s: String = slice.parse().ok()?;
    println!("{}", s);
    Some(s[1..s.len()-1].into())
}

fn main() {
    let lex = Token::lexer("\"this is a test\"");
    for token in lex {
        println!("{:?}", token);
    }
}
```

Notably the print is never executed within the `string` callback. Also, none of the other regex patterns accept a double quote as the first character. Am I missing something or is this a bug? I only discovered this crate last night so I would not rule out the possibility that I'm missing something haha.

**Comment by maciejhirsz** [comment]
Lexing in logos is greedy, so your string literal pattern will consume the entire input to the end once it reaches `.*`. This is, currently at least, by design. You can easily fix it with: `r#""[^"]*""#` (note that this will not handle escapes if you need them).

Sidenote: you don't need to parse a string slice to a `String`, so this can be simpler:

```rust
fn string(lex: &mut LogosLexer<TokenType>) -> Option<String> {
    let slice = lex.slice();
    Some(slice[1..slice.len()-1].into())
}
```

It would be even simpler and faster still if you swap all `String`s for `&str`s in the token definitons to avoid allocations.

**Comment by evandp** [comment]
Ah gotcha, that makes sense. Thank you for the quick reply and happy holidays!

**Comment by maciejhirsz** [comment]
Happy holidays :)
