### ISSUE TITLE
better docs for derive macro

### ISSUE THREAD

**Issue by rogpeppe** [maciejhirsz/logos#214]
I might have missed it, but I've been looking for proper reference docs for what can be put in the derive macro directives and all I've found is https://docs.rs/logos/0.12.0/logos/derive.Logos.html which doesn't have any docs at all, and the "by example" docs at the top level which don't provide enough detail.

As an example of a few questions I have that don't seem to be answered by the existing docs:

- what flavour of regexps are supported? (PCRE? POSIX? backtracking? capture groups? etc)
- how does the "skip" thing work - in the examples, a skip rule is attached to an `Error` variant, but does it have to be that way? Could it be attached to any variant without the behaviour changing?
- what do the `#[end]`, `#[extras]` and `#[logos]` directives do?
- if there are several directives attached to a single enum variant, is it possible for the callback to tell which one was selected?

As the least formal part of the Logos API, the derive macros could really use some more comprehensive documentation.
Perhaps it exists already - if so, it would be good to link to it from a prominent place :)

**Comment by maciejhirsz** [comment]
Just to answer these here for now, in order:

+ Subset of what [`regex-syntax` supports](https://docs.rs/regex/1.5.4/regex/#syntax), sans: capturing groups (all groups are non-capturing), boundaries, other stuff that eludes me right now.
+ `skip` is applied to the single pattern it's attached to, it can be attached to any variant, and the way it works is quite simple: if the pattern is matched, instead of producing a token, the lexer will start a new match from scratch.
+ `#[end]` is deprecated, as is `#[extras]`. `#[logos]` is the new "namespace" attribute, and you can use it to set other functionality on the lexer, e.g.: `#[logos(extras = Type)]` will set the `Logos::Extras` associated type to `Type` in the derived impl. Extras must implement `Default`, will be instantiated along with the `Lexer`, and you can access them [by field](https://docs.rs/logos/0.12.0/logos/struct.Lexer.html#structfield.extras) if you need arbitrary state on the lexer (which [can be useful in callbacks](https://github.com/maciejhirsz/ramhorns/blob/9f2ed4d3d173cc835dc0a281662b0a8e87a348f2/ramhorns/src/template/parse.rs#L21-L26)).
+ You can have multiple different patterns, each with its own callback, producing the same enum variant.

**Comment by evbo** [comment]
@maciejhirsz what you wrote about `extras` and `callbacks` just made all the difference for me, thank you! Was struggling with a very annoying collision where depending on the context of how many indents I needed to lex differently. Had no idea `extras` existed and that solved my problem elegantly!

**Comment by jeertmans** [comment]
Closing this as I feel this is now documented in the handbook. If needed, feel free to re-open this issue!
