### ISSUE TITLE
Need help identifying the cause of a Logos-related compiler error

### ISSUE THREAD

**Issue by AshtonSnapp** [maciejhirsz/logos#219]
Greetings! First off, hope everyone is having an awesome day because currently I am not.

Second, I have been encountering a strange compiler error that appears to be related to this project, logos. As a short summary, I have a function which takes in a file from main, and throws each line of the file into a logos lexer, which is then .spanned(). Then it goes through the iterator and checks each Token. If it's a Token::Error, it either eprintln!()s or errs.push()es an error message depending on whether verbose mode is active. Otherwise, it pushes the Token into a Vec, which is then pushed into another Vec once all the tokens in the line have been checked. Once the whole file has been processed, it checks if errs has at least one error message in it. If it does, Err(errs).

Originally, this function (called tok()) would return a Vec<&str> on Err(), but due to a missing lifetime parameter error I just removed the &. Now, on every single callback function I wrote, I'm getting an E0277 because logos is doing something with [u8], even though I'm passing in each line as an &str. I don't know what's causing this error, and due to that I don't know how to fix it. Since this is a logos-related error, I figured I'd come over to here to seek help with this issue (because I honestly need it).

If you need to look at anything:

- GitHub Actions Rust Build Run: [https://github.com/AshtonSnapp/chasm/runs/3072076214?check_suite_focus=true](https://github.com/AshtonSnapp/chasm/runs/3072076214?check_suite_focus=true)
- lex.rs (where everything lexer and logos related happens): [https://github.com/AshtonSnapp/chasm/blob/master/src/lex.rs](https://github.com/AshtonSnapp/chasm/blob/master/src/lex.rs)

**Comment by maciejhirsz** [comment]
This has nothing to do with Logos. `Vec<str>` and `Result<[u8], ()>` are not valid types and cannot be constructed since `str` and `[u8]` are unsized types so you can't put them on stack or vec raw since the compiler doesn't know how big they are. They need a fat pointer, which is either a ref (`&str` or `&[u8]`) or any of the owned pointer types (`Box<str>` or `Box<[u8]>` would be the most common), and rustc even tells you that in the error messages :).

The reason why some of the errors emit from the `Logos` derive is because the proc macro will copy-paste your types verbatim.

**Comment by AshtonSnapp** [comment]
Okay, that makes more sense.

I still wonder why some of the errors appear to emit from the callback functions that don't return a str or [u8] however.

**Comment by AshtonSnapp** [comment]
Alright, I've got all of that fixed in my project. All I have left to do is implement the address and immediate callbacks (which is going to be a PITA), but after that I hopefully won't have any compile errors until I start writing the parser.

**Comment by maciejhirsz** [comment]
> I still wonder why some of the errors appear to emit from the callback functions that don't return a str or [u8] however.

rustc explanation is pretty good:

```
    --> src/lex.rs:117:15
    |
117 | fn label(lex: &mut Lexer<Token>) -> Result<IdentifierInfo, ()> {
    |               ^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    | 
   ::: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/logos-0.12.0/src/lexer.rs:12:27
    |
12  | pub struct Lexer<'source, Token: Logos<'source>> {
    |                           ----- required by this bound in `logos::Lexer`
    |
    = help: within `Token`, the trait `Sized` is not implemented for `[u8]`
```

The `Logos` has an associated function [`lex`](https://docs.rs/logos/0.12.0/logos/trait.Logos.html#tymethod.lex) which returns `Self`, so the trait has to have the trait bound to the `Sized`.

There is also the implementation detail of `Lexer` containing a single `Token: Logos` in a field for pretty esoteric reasons, so that's why the entire lexer is marked as unsized when the token contains a `[u8]` (can't construct a token -> can't construct the lexer).

**Comment by AshtonSnapp** [comment]
That makes sense.
