### ISSUE TITLE
Macro output in #[regex()]

### ISSUE THREAD

**Issue by ccleve** [maciejhirsz/logos#267]
I'm porting a lexer I wrote in Antlr to Logos. It has some fairly complex rules which involve several different productions combined in different ways. For example:

```
FANCY_TOKEN: (FOO|BAR|BAH)* (THIS|OR|THAT) (FOO|BAR)+
FOO: {SOME_OTHER_COMPLICATED_THING)
BAR: ...
```

It would be really difficult to build a literal regex string for FANCY_TOKEN because it would be long and have a fair amount of repetition.

So... I thought that I could assemble such a string at compile time using a macro. I could execute all the code to build the string before putting it in the #[regex()]. Unfortunately, this fails:

```
macro_rules! letters {
    () => {
        "[a-zA-Z]"
    };
}

#[derive(Logos, Debug, PartialEq)]
enum Token {
    #[regex(letters!())]
    word,
}
```

```
error: expected literal
  --> src/query/logos/index_lexer.rs:16:13
   |
16 |     #[regex(letters!())]
   |             ^^^^^^^

```

Is there a way to make this work?

Also, constants fail with the same error message: 

`const LETTERS: &'static str = "[a-zA-Z]";`
```

error: expected literal
  --> src/query/logos/index_lexer.rs:16:13
   |
16 |     #[regex(LETTERS)]
   |       
```      ^^^^^^^

**Comment by maciejhirsz** [comment]
I'm afraid that's just a limitation of rustc where the token stream inside the attribute does not evaluate macros, and rightfully so, since that token stream can literally be anything, there are no syntax rules for it, so no way for the compiler to catch a macro invocation in that place.

You can do what you're trying to do [using subpatterns though](https://github.com/maciejhirsz/logos/blob/56afbaa6667dc74faea202ab6e8a43e18d3775ad/tests/tests/advanced.rs#L4-L16).

**Comment by radrow** [comment]
Why not allow const expressions then? It is a bit nicer to store keywords in a global vector for instance.
