### ISSUE TITLE
Running into `precise captures on `impl Trait` are experimental` with 0.14.3

### ISSUE THREAD

**Issue by tdomhan** [maciejhirsz/logos#446]
Hi! I just updated my cargo dependencies and ran into issue with 0.14.3 that is fixed by downgrading to 0.14.3. I'm using logos indirectly via the interim. The following derive macro: 
https://github.com/conradludgate/interim/blob/master/src/parser.rs#L26

raises the error 
```
precise captures on `impl Trait` are experimental
```
when using 0.14.3. 

My rustc version: `rustc 1.82.0-nightly (28a58f2fa 2024-07-31)`

**Comment by jeertmans** [comment]
Hi! Thanks for reporting your issue!



> Hi! I just updated my cargo dependencies and ran into issue with 0.14.3 that is fixed by downgrading to 0.14.3. 

I guess you mean downgrading to 0.14.2?


> My rustc version: `rustc 1.82.0-nightly (28a58f2fa 2024-07-31)`

Can you try upgrading your nightly tool chain? I think it requires a feature that was stabilised in 1.84-nightly.

**Comment by tdomhan** [comment]
Thanks for taking a look! Actually another dependency I have was not compatible with the current nightly which is why it's a bit outdated. If this is not a problem on a recent version feel free to close the issue. I'll for now use the previous minor version and eventually upgrade my nightly rustc.

**Comment by jeertmans** [comment]
Hi @tdomhan, sorry for the late reply.

I have some doubt about which direction we should take regarding support of nightly version. In my opinion, nightly versions are by definition unstable and users should be careful when using them instead of stable Rust.

So I'll close this issue, as I don't think it makes sense to publish a patch for an older version of nightly Rust (but maybe I am wrong).
