### ISSUE TITLE
Line/column info?

### ISSUE THREAD

**Issue by mattgreen** [maciejhirsz/logos#89]
Hi, thank you for this crate! I love the combo of declarative + performant infrastructure.

Was wondering if you'd be open to a PR for line and column info. To do this, I'd like to add a method to `Lexer` that returns a `Span` representing the extent of the token. This would probably be a pair of `Pos` structures, where a `Pos` is a line/column tuple. Tracking this information isn't a big deal, but there may be some performance implications involved when scanning each token for newlines.

What do you think?

**Comment by jyn514** [comment]
@mattgreen as an alternative, you could add an `Extras` type that counts the line and column using `on_advance()`

**Comment by maciejhirsz** [comment]
Using `Extras` is one way to do it. Before I stabilize 0.10 I want to add an option to add callbacks to custom trivia, so you can define `\n` separate from other whitespace and have a callback that increments line count.

Personally, I find that you only really need this information when doing error reporting, and it tends to be a good approach to trade error handling performance for general performance. If you have a token you want to report the error for, find first `\n` going backwards from it's start position to find column start, and then `source[..where_that_line_starts].lines().count()` will give you line information.

**Comment by brendanzab** [comment]
I definitely would prefer it if logos continued to use byte ranges!

@mattgreen you might find it useful to look at [how I do this in `codespan-reporting`](https://github.com/brendanzab/codespan/blob/44a88ee938cfbdff0f7ea84b86b256b6aa5c4aab/codespan-reporting/src/files.rs). You cache the byte index of each line, then do a binary search to find where a given byte index starts. This is something that can happen in the diagnostic reporting because that is usually off the critical path.

**Comment by maciejhirsz** [comment]
Since I'm working on callbacks in #103, this issue would probably be a good idea to discuss how those should wore with trivia/whitespace/skippable tokens. I think ideally I'd want to get rid of the `Extras` trait (extras as a global state would be still there, I just want to make it usable without having to `impl Extras for MyExtras {}`), and I think it might be a good idea to _not_ have default whitespace rules.

Anyway, my current idea is to add `skip` or `trivia` flag to `regex`/`token` definitions, and you could use the `#[end]` or `#[error]` variants to define those. Combined with new callbacks, you could collect line positions roughly like so:

```rust
struct Extras {
    line_heads: Vec<usize>,
}

#[derive(Logos)]
#[logos(extras = Extras)]
enum Token {
    #[regex(trivia, r"[ \t\f]")]
    #[regex(trivia, r"\n", |lex| {
        // This callback doesn't produce a token, but you can still use it to
        // get the byte position of every new line character
        let head = lex.range().end;
        lex.extras.line_heads.push(head));
    }]
    #[error]
    Error

    // ...
}
```

Callbacks would be obviously blind to new lines inside other tokens (if you have string token that can span multiple lines, for example), so those cases would have to be handled somehow, but that's no different with `on_whitespace` currently.

**Comment by luca-i** [comment]
> @mattgreen as an alternative, you could add an `Extras` type that counts the line and column using `on_advance()`

Could you please give me some hint how `on_advance(&mut self)` could differentiate between spaces and new lines?
Thx, Luca-

**Comment by maciejhirsz** [comment]
@luca-i there isn't a way to do this since 0.10 unfortunately.

I've been working on implementing trivia with callbacks, roughly analog to my comment above, which will make it possible to have a callback on a specific definition like `\n` that will not emit a token. I reckon by the end of today it should be merged and deployed  as 0.11-rc4.

**Comment by maciejhirsz** [comment]
@luca-i -rc4 is out, here is a test that's binding `\n` to a callback:

https://github.com/maciejhirsz/logos/blob/0e914ef4ce0043b38f74b24d602b49f2b519f579/tests/tests/simple.rs#L34-L41

The definition is technically bound to `Error`, but since the callback returns `Skip` it doesn't matter.

**Comment by luca-i** [comment]
> @luca-i -rc4 is out, here is a test that's binding `\n` to a callback:
> 
> https://github.com/maciejhirsz/logos/blob/0e914ef4ce0043b38f74b24d602b49f2b519f579/tests/tests/simple.rs#L34-L41
> 
> The definition is technically bound to `Error`, but since the callback returns `Skip` it doesn't matter.

Thank you!

**Comment by maciejhirsz** [comment]
This should be easy to handle now with callbacks and whitespace handling being explicit.

**Comment by mattgreen** [comment]
These changes look fantastic. Thank you!
