### ISSUE TITLE
`static LUT: [bool; 256]` compression planned?

### ISSUE THREAD

**Issue by Evrey** [maciejhirsz/logos#99]
Would it be beneficial perf-wise to turn `static LUT: [bool; 256]` into a `static LUT: [usize; 256 / 8 / size_of::<usize>()]` instead and then index packed bits? At least it's more space efficient, which may be attractive for people with more complicated token rules than I have. 

Doing a quick `Ctrl+F` through my generated code, I have 179 such tables. That'd be a reduction from about 44KiB worth of lookup tables to about 5KiB.

On a similar note I have 57 `const LUT: [u8; 256]`s. I dunno whether they are optimised away or kept, but if kept, most of them seem to only contain numbers `<16`, most of them are less than ¼ filled, and most of them cluster occurring non-zero entries. There is potential for selectively compressing some `LUT`s to `[u8; 128]`s for 4-bit look-ups, and even sparse table allocations. But those space optimisations may have too much of a runtime impact. Dunno.

**Comment by maciejhirsz** [comment]
The short answer is: no.

The long answer is: optimizing these for memory efficiency kills their purpose, which is to reduce number of instructions you have to do to check a byte. To index into a bitmap you have to:
+ Do a division with a remainder (powers of 2, but still).
+ Do a bitshift.
+ Do a bitand or xor or something.

There might be embedded platforms where the LUTs are trashing cache, but in all of those cases it would probably be better not to have a LUT in the first place.

That said, there are things I want to do that will reduce the number of tables produced by codegen, (which right now is rather aggressive because it was easy to do :P):
1. There is probably a bunch of boolean LUTs that can be avoided if I properly de-cascade all involved ranges. For example: if you have range `[a-i]` going to node 1, `[h]` going to node 2, `[j-z]` going to node 1 again, it can be done with a simple `match byte { b'h' => ..., b'a'..=b'z' => ..., _ => }`, where as now it will produce a LUT. Writing a decascading algo for ranges would be a good first issue :P.
2. The LUTs with numbers that I use to force rustc to make nice jump tables are probably redundant. That is, there are likely cases where one table that uses values 1-4 is is perfectly overlapping with another table that uses values 1-6, which means we could re-use the latter and just ignore 5 & 6 along 0. It might be better to shift the usable values from 1+ to 0+ and set default miss value to 0xFF, only time and benchmarks will tell :).

**Comment by Evrey** [comment]
> Writing a decascading algo for ranges would be a good first issue :P

Hint-hint, nudge-nudge. ;) I may have myself at it, but no guarantees.

> It might be better to shift the usable values from 1+ to 0+ and set default miss value to 0xFF

This does indeed sound interesting. And makes me once more wish that Rust had more useful sentinel types than just `NonZero`.

Back on the matter of indexing into a bit-packed array, one would have to:

- Clear the bottom bits of the index. 1 cycle, throughput ¼ on x86. Very high chance of being run in parallel with another instruction.
- Do a memory load, which may take 2 to 4 cycles on cache hits.
- On x86, just do `BT table_word, idx`, where `idx` is the raw byte as the function received it. This instruction performs a modulo on `idx`. 1 cycle, throughput ¼.
- Depending on how bad LLVM feels like doing inlining, another `SETcc` instruction is necessary, 1 cycle, ½ throughput.

So, absolute best case all extra instructions get ILPed away in benchmarks. Mediocre case it's an increase from 2 cycles L1 hit to 4 or 5 cycles on an L1 hit. Worst case is always a cache miss hitting the RAM refresh timer, resulting in thousands of cycles of stalling.

You sound like you have benched all this already, though? In that case: Never mind.

**Comment by maciejhirsz** [comment]
Yeah. And if we are to do arch specific shenanigans, it might be better to just [go straight for simd](https://github.com/raphlinus/pulldown-cmark/blob/aa669c0ebea8ec7760eade4735c6525047b6e7d0/src/simd.rs#L24-L44).

**Comment by Evrey** [comment]
All right, then. °^° I'll close this issue as »not relevant (yet)«, then.

**Comment by maciejhirsz** [comment]
I figured out something that might be useful: If the pattern match is for bytes within a range of 64 from one another (that is `highest_byte - lowest_byte < 64`) instead of using a table, we can do a lookup on a `u64` bitset. [Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=b561092ffa756088030faf6689267d0e):

```rust
#[no_mangle]
fn packed_low64(bytes: &[u8]) -> usize {
    const MASK: u64 = (1 << 34) | (1 << 32) | (1 << 30);
    
    bytes
        .iter()
        .take_while(|byte| match 1u64.checked_shl((**byte as u32) % 64) {
            Some(shift) => shift & MASK != 0,
            None => false,
        })
        .count()
}

#[no_mangle]
fn lut(bytes: &[u8]) -> usize {
    const LUT: [bool; 256] = {
        let mut lut = [false; 256];
        lut[34] = true;
        lut[32] = true;
        lut[30] = true;
        lut
    };

    bytes.iter().take_while(|byte| LUT[**byte as usize]).count()
}
```

ASM:

```asm
packed_low64:
        xor     eax, eax
        test    rsi, rsi
        je      .LBB0_4
        movabs  rcx, 22548578304
.LBB0_2:
        movzx   edx, byte ptr [rdi + rax]
        bt      rcx, rdx
        jae     .LBB0_4
        add     rax, 1
        cmp     rsi, rax
        jne     .LBB0_2
.LBB0_4:
        ret

lut:
        xor     eax, eax
        test    rsi, rsi
        je      .LBB1_4
        lea     rcx, [rip + .L__unnamed_1]
.LBB1_2:
        movzx   edx, byte ptr [rdi + rax]
        cmp     byte ptr [rdx + rcx], 0
        je      .LBB1_4
        add     rax, 1
        cmp     rsi, rax
        jne     .LBB1_2
.LBB1_4:
        ret

.L__unnamed_1:
        .asciz  "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\001\000\001\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
```

This optimizes much nicer than I thought it would, effectively we replaces `cmp` with `bt`. This is kind of the best case scenario here since it assumes highest byte value in pattern is 63, but adding a single subtraction shouldn't cost much.

**Comment by Evrey** [comment]
Huh, sparse tables and compressed tables in one go. This is a sexy optimisation, lad!

**Comment by maciejhirsz** [comment]
Turns out I fucked it up and my `checked_shl` doesn't do anything there, since I also do `% 64` :man_facepalming:.

That said, I did implement this, and even though there is more instructions in this version, including some unfortunate branches and an extra `sub` (benching `[a-zA-Z]`, so needed to bring the values down), performance is comparable with a full blown LUT, and it should be much more cache friendly, so I think I'm gonna leave it there :).

Also, that explains why the naive version does a `cmp` before `bt`. Compiler turns out smarter once again :D.

**Comment by Evrey** [comment]
Can put the bytes on the LUT name, like `LUT_DEADBEEF`.

**Comment by Evrey** [comment]
Oh, does this also open up new opportunities to also compress `const LUT: [u8; 256]`?

**Comment by maciejhirsz** [comment]
I've benched `[u64; 4]` bitset variant, and it butchered performance. I reckon that here it works because you trade memory access (table is put in a register from an inline) for more instructions.

**Comment by Evrey** [comment]
I'd blame it on immediate vs. random memory loads.

**Comment by maciejhirsz** [comment]
Ok, I've read the ASM, I've run preliminary benchmarks.

Turns out there is basically no difference in performance between a table of `bool`s matching `LUT[byte as usize]`, and table of `u8`s matching `LUT[byte as usize] & BITMASK > 0` where `BITMASK` is 1 shifted left by 0-7.

hot loop for `[bool; 256]`:
```asm
.LBB0_2:
        movzx   edx, byte ptr [rdi + rax]
        cmp     byte ptr [rdx + rcx], 0
        je      .LBB0_4
        add     rax, 1
        cmp     rsi, rax
        jne     .LBB0_2
```

hot loop for `[u8; 256]` using `4` as a mask:
```asm
.LBB1_2:
        movzx   edx, byte ptr [rdi + rax]
        test    byte ptr [rdx + rcx], 4
        je      .LBB1_4
        add     rax, 1
        cmp     rsi, rax
        jne     .LBB1_2
```

This is so obvious now that I think about this. Instead of trying to compress the tables, we can just stack 8 tables into a single `[u8; 256]`. Given that code gen works recursively through the state machine graph, this should also play really nicely with cache locality.

**Comment by maciejhirsz** [comment]
[Implemented](https://github.com/maciejhirsz/logos/blob/a20d20a53dbef28f5573d7a0dd29302adb42d4d0/logos-derive/src/generator/table.rs) this just now, got a tad of a performance boost across benchmarks, while the code that's being spit out is smaller, so win-win!

Actual generated code (look at those `255`s!):
```rust
        static COMPACT_TABLE_0: [u8; 256] = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 127, 127, 127, 127, 127,
            127, 127, 127, 127, 127, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255,
            255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
            255, 0, 0, 0, 0, 255, 0, 223, 255, 255, 255, 239, 255, 255, 255, 253, 255, 255, 255,
            255, 255, 255, 255, 255, 255, 191, 251, 255, 247, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        ];

        // ...

        #[inline]
        fn pattern0(byte: u8) -> bool {
            COMPACT_TABLE_0[byte as usize] & 1 > 0
        }

        // ...

        #[inline]
        fn pattern4(byte: u8) -> bool {
            COMPACT_TABLE_0[byte as usize] & 2 > 0
        }
        #[inline]
        fn pattern5(byte: u8) -> bool {
            COMPACT_TABLE_0[byte as usize] & 4 > 0
        }
        #[inline]
        fn pattern6(byte: u8) -> bool {
            COMPACT_TABLE_0[byte as usize] & 8 > 0
        }
        #[inline]
        fn pattern7(byte: u8) -> bool {
            COMPACT_TABLE_0[byte as usize] & 16 > 0
        }

        // ...

        #[inline]
        fn pattern8(byte: u8) -> bool {
            COMPACT_TABLE_0[byte as usize] & 32 > 0
        }
        #[inline]
        fn pattern9(byte: u8) -> bool {
            COMPACT_TABLE_0[byte as usize] & 64 > 0
        }

        // ...

        #[inline]
        fn pattern10(byte: u8) -> bool {
            COMPACT_TABLE_0[byte as usize] & 128 > 0
        }
```

8 patterns, 1 table :tada:.

**Comment by Evrey** [comment]
Smart optimisation! You should write a big blog post series about v0.11. I love reading about black magic like this.

**Comment by maciejhirsz** [comment]
@Evrey you've asked: https://maciej.codes/2020-04-19-stacking-luts-in-logos.html

**Comment by Evrey** [comment]
Hey, pretty great write-up, thanks. =)

Definitely will watch the creativity talk.
